- name: INNOQ
  icon: fa-briefcase
  link: "https://www.innoq.com/en/staff/lars-hupel/"
- name: Google Scholar
  icon: fa-graduation-cap
  link: "https://scholar.google.com/citations?user=VdxLaDEAAAAJ"
- name: GitHub
  icon: fa-github
  link: "https://github.com/larsrh"
- name: Stack Overflow
  icon: fa-stack-overflow
  link: "https://stackoverflow.com/users/4776939/larsrh"
- name: Twitter
  icon: fa-twitter
  link: "https://twitter.com/larsr_h"
- name: Instagram
  icon: fa-instagram
  link: "https://instagram.com/larsr_h"
- name: Speaker Deck
  icon: fa-desktop
  link: "https://speakerdeck.com/larsrh"
