- name: INNOQ
  icon: 💼
  link: "https://www.innoq.com/en/staff/lars-hupel/"
- name: Google Scholar
  icon: 🎓
  link: "https://scholar.google.com/citations?user=VdxLaDEAAAAJ"
- name: GitHub
  icon: 💻
  link: "https://github.com/larsrh"
- name: Twitter
  icon: 🐦
  link: "https://twitter.com/larsr_h"
- name: Instagram
  icon: 📷
  link: "https://instagram.com/larsr_h"
- name: Speaker Deck
  icon: 🎙️
  link: "https://speakerdeck.com/larsrh"
- name: XING
  icon: 👔
  link: "https://www.xing.com/profile/Lars_Hupel"
- name: LinkedIn
  icon: 🕴️
  link: "https://www.linkedin.com/in/dr-lars-hupel-64912b222/"
